[package]
name = "dfberry-rust-axum-server-source-board"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = { version = "0.7.4" }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
tower-http = { version = "0.5.0", features = ["cors"] }
uuid = { version = "1.3.0", features = ["v4","serde"] }

[[bin]]
name = "dfberry-rust-axum-server-source-board"
path = "src/main.rs"