[package]
name = "dfberry-rust-axum-server-source-board"
version = "0.2.0"
edition = "2021"
publish = false

[dependencies]
axum = { version = "0.7.5" }
axum-extra = { version = "0.9.3", features = ["typed-header"] }
tokio = { version = "1.39.3", features = ["full"] }
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
serde_derive = "1.0.208"
tower-http = { version = "0.5.2", features = ["cors"] }
uuid = { version = "1.10.0", features = ["v4","serde"] }
urlencoding = "2.1.3"
octocrab = "0.39.0"
http = "1.1.0"
http-serde-ext = "1.0.2"
dotenv = "0.15.0"
tower = "0.5.0"
anyhow = "1.0.86" 
toml = "0.8.19"
url = "2.5.2"
chrono = "0.4.38"

[[bin]]
name = "dfberry-rust-axum-server-source-board"
path = "src/main.rs"
