# The runtime environment has ADMIN_KEY and the request query parameter is admin_key
# The values must match
GET http://localhost:4000/config?admin_key={{$dotenv %ADMIN_KEY}} HTTP/1.1
content-type: application/json